### ISSUE TITLE
how to find wifi & bluetooth?

### ISSUE THREAD

**Issue by lwj1994** [JackTheCode/opencore-5600x-B550M-Mortar#1]
my board is b550m-mortar-wifi

**Comment by JackTheCode** [comment]
try this 
* WIFI:`https://github.com/OpenIntelWireless/itl`
* Bluetooth: `https://github.com/OpenIntelWireless/IntelBluetoothFirmware`

**Comment by lwj1994** [comment]
> try this
> 
> * WIFI:`https://github.com/OpenIntelWireless/itl`
> * Bluetooth: `https://github.com/OpenIntelWireless/IntelBluetoothFirmware`

i tried，but failed. don't work at all

**Comment by JackTheCode** [comment]
Unfortunately, I can't help my mobo doesn't have Wifi or Bluetooth
